# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: ta.poulsen@gmail.com
AuthorName: Thomas Agersten Poulsen
Indentation: 4
JuliaMinVersion: '1.10'
License: MIT
PackageName: MusicalTuningSystems
PackageOwner: tp2750
PackageUUID: 46b061b3-782d-5b83-b0fe-6be4b8bf45df
_commit: v0.8.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
